import { Skill } from './types'

export interface PreinstalledSkillDefinition extends Skill {
  owner: string
  upstreamPath: string
  tags: string[]
}

export const PREINSTALLED_SKILLS: PreinstalledSkillDefinition[] = [
  {
    id: 'sophie-optimizer',
    name: 'Sophie Optimizer',
    version: '1.0.0',
    description: 'Automated context health management for OpenClaw sessions.',
    inputsSchemaName: 'default',
    permissions: [],
    origin: 'preinstalled',
    category: 'context',
    source: 'openclaw/skills',
    status: 'preinstalled',
    preinstalled: true,
    tools: ['context_health', 'context_compact'],
    elevated_permissions: false,
    path: 'src/skills/sophie-optimizer/SKILL.md',
    owner: 'zayresz',
    upstreamPath: 'skills/zayresz/sophie-optimizer/SKILL.md',
    tags: ['context', 'maintenance', 'health'],
  },
  {
    id: 'context-anchor',
    name: 'Context Anchor',
    version: '1.0.0',
    description: 'Recover context after compaction by scanning memory and anchor points.',
    inputsSchemaName: 'default',
    permissions: [],
    origin: 'preinstalled',
    category: 'context',
    source: 'openclaw/skills',
    status: 'preinstalled',
    preinstalled: true,
    tools: ['context_restore', 'anchor_scan'],
    elevated_permissions: false,
    path: 'src/skills/context-anchor/SKILL.md',
    owner: 'boscoeuk',
    upstreamPath: 'skills/boscoeuk/context-anchor/SKILL.md',
    tags: ['context', 'rehydration'],
  },
  {
    id: 'continuity',
    name: 'Continuity Framework',
    version: '1.0.1',
    description: 'Asynchronous reflection and memory integration between sessions.',
    inputsSchemaName: 'default',
    permissions: [],
    origin: 'preinstalled',
    category: 'memory',
    source: 'openclaw/skills',
    status: 'preinstalled',
    preinstalled: true,
    tools: ['memory_reflect', 'memory_integrate'],
    elevated_permissions: false,
    path: 'src/skills/continuity/SKILL.md',
    owner: 'riley-coyote',
    upstreamPath: 'skills/riley-coyote/continuity/SKILL.md',
    tags: ['memory', 'timeline', 'reflection'],
  },
  {
    id: 'chaos-mind',
    name: 'Chaos Mind',
    version: '0.1.3',
    description: 'Hybrid semantic + keyword memory search and storage engine.',
    inputsSchemaName: 'default',
    permissions: [],
    origin: 'preinstalled',
    category: 'memory-search',
    source: 'openclaw/skills',
    status: 'preinstalled',
    preinstalled: true,
    tools: ['memory_search', 'memory_store'],
    elevated_permissions: false,
    path: 'src/skills/chaos-mind/SKILL.md',
    owner: 'hargabyte',
    upstreamPath: 'skills/hargabyte/chaos-mind/SKILL.md',
    tags: ['memory', 'search', 'hybrid'],
  },
  {
    id: 'public',
    name: 'Public (Path Alias)',
    version: '1.0.3',
    description: 'Mapped from skills/sahanico/molt/web/public/SKILL.md. Requested companion-monitor variant is tracked in SKILLS_TODO.md.',
    inputsSchemaName: 'default',
    permissions: [],
    origin: 'preinstalled',
    category: 'activity',
    source: 'openclaw/skills',
    status: 'preinstalled',
    preinstalled: true,
    tools: ['activity_stream', 'agent_presence'],
    elevated_permissions: false,
    path: 'src/skills/public/SKILL.md',
    owner: 'sahanico',
    upstreamPath: 'skills/sahanico/molt/web/public/SKILL.md',
    tags: ['activity', 'streaming'],
  },
  {
    id: 'system-monitor',
    name: 'System Monitor',
    version: '1.0.0',
    description: 'Monitor CPU, RAM, and GPU status for local or server runtime health.',
    inputsSchemaName: 'default',
    permissions: [],
    origin: 'preinstalled',
    category: 'reliability',
    source: 'openclaw/skills',
    status: 'preinstalled',
    preinstalled: true,
    tools: ['system_stats'],
    elevated_permissions: false,
    path: 'src/skills/system-monitor/SKILL.md',
    owner: 'zerofire03',
    upstreamPath: 'skills/zerofire03/system-monitor/SKILL.md',
    tags: ['monitoring', 'resources'],
  },
  {
    id: 'security-monitor',
    name: 'Security Monitor',
    version: '1.0.0',
    description: 'Real-time security monitoring for unusual tool activity and intrusion signals.',
    inputsSchemaName: 'default',
    permissions: [],
    origin: 'preinstalled',
    category: 'security',
    source: 'openclaw/skills',
    status: 'preinstalled',
    preinstalled: true,
    tools: ['security_scan', 'security_alerts'],
    elevated_permissions: false,
    path: 'src/skills/security-monitor/SKILL.md',
    owner: 'chandrasekar-r',
    upstreamPath: 'skills/chandrasekar-r/security-monitor/SKILL.md',
    tags: ['security', 'alerts'],
  },
  {
    id: 'brainrepo',
    name: 'BrainRepo',
    version: '1.0.0',
    description: 'Personal knowledge repository for capture, organization, and retrieval.',
    inputsSchemaName: 'default',
    permissions: [],
    origin: 'preinstalled',
    category: 'memory',
    source: 'openclaw/skills',
    status: 'preinstalled',
    preinstalled: true,
    tools: ['quick_capture', 'knowledge_retrieve'],
    elevated_permissions: false,
    path: 'src/skills/brainrepo/SKILL.md',
    owner: 'codezz',
    upstreamPath: 'skills/codezz/brainrepo/SKILL.md',
    tags: ['knowledge', 'capture'],
  },
]
