/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PipelinesRouteImport } from './routes/pipelines'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as DevRouteImport } from './routes/dev'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BrowserRouteImport } from './routes/browser'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as ImperialVaultRouteRouteImport } from './routes/imperial-vault/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImperialVaultIndexRouteImport } from './routes/imperial-vault/index'
import { Route as ImperialVaultViralScoreRouteImport } from './routes/imperial-vault/viral-score'
import { Route as ImperialVaultTerminalRouteImport } from './routes/imperial-vault/terminal'
import { Route as ImperialVaultSandboxRouteImport } from './routes/imperial-vault/sandbox'
import { Route as ImperialVaultPipelineRouteImport } from './routes/imperial-vault/pipeline'
import { Route as ImperialVaultOverlayRouteImport } from './routes/imperial-vault/overlay'
import { Route as ImperialVaultMusicRouteImport } from './routes/imperial-vault/music'
import { Route as ImperialVaultIntelligenceRouteImport } from './routes/imperial-vault/intelligence'
import { Route as ImperialVaultIntelRouteImport } from './routes/imperial-vault/intel'
import { Route as ImperialVaultFootageRouteImport } from './routes/imperial-vault/footage'
import { Route as ImperialVaultFactsRouteImport } from './routes/imperial-vault/facts'
import { Route as ImperialVaultDiscordRouteImport } from './routes/imperial-vault/discord'
import { Route as ImperialVaultCookiesRouteImport } from './routes/imperial-vault/cookies'
import { Route as ImperialVaultCalendarRouteImport } from './routes/imperial-vault/calendar'
import { Route as ImperialVaultAlertsRouteImport } from './routes/imperial-vault/alerts'
import { Route as DevApprovalsRouteImport } from './routes/dev/approvals'

const PipelinesRoute = PipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowserRoute = BrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ImperialVaultRouteRoute = ImperialVaultRouteRouteImport.update({
  id: '/imperial-vault',
  path: '/imperial-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImperialVaultIndexRoute = ImperialVaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImperialVaultRouteRoute,
} as any)
const ImperialVaultViralScoreRoute = ImperialVaultViralScoreRouteImport.update({
  id: '/viral-score',
  path: '/viral-score',
  getParentRoute: () => ImperialVaultRouteRoute,
} as any)
const ImperialVaultTerminalRoute = ImperialVaultTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => ImperialVaultRouteRoute,
} as any)
const ImperialVaultSandboxRoute = ImperialVaultSandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => ImperialVaultRouteRoute,
} as any)
const ImperialVaultPipelineRoute = ImperialVaultPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => ImperialVaultRouteRoute,
} as any)
const ImperialVaultOverlayRoute = ImperialVaultOverlayRouteImport.update({
  id: '/overlay',
  path: '/overlay',
  getParentRoute: () => ImperialVaultRouteRoute,
} as any)
const ImperialVaultMusicRoute = ImperialVaultMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => ImperialVaultRouteRoute,
} as any)
const ImperialVaultIntelligenceRoute =
  ImperialVaultIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => ImperialVaultRouteRoute,
  } as any)
const ImperialVaultIntelRoute = ImperialVaultIntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => ImperialVaultRouteRoute,
} as any)
const ImperialVaultFootageRoute = ImperialVaultFootageRouteImport.update({
  id: '/footage',
  path: '/footage',
  getParentRoute: () => ImperialVaultRouteRoute,
} as any)
const ImperialVaultFactsRoute = ImperialVaultFactsRouteImport.update({
  id: '/facts',
  path: '/facts',
  getParentRoute: () => ImperialVaultRouteRoute,
} as any)
const ImperialVaultDiscordRoute = ImperialVaultDiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => ImperialVaultRouteRoute,
} as any)
const ImperialVaultCookiesRoute = ImperialVaultCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => ImperialVaultRouteRoute,
} as any)
const ImperialVaultCalendarRoute = ImperialVaultCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => ImperialVaultRouteRoute,
} as any)
const ImperialVaultAlertsRoute = ImperialVaultAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => ImperialVaultRouteRoute,
} as any)
const DevApprovalsRoute = DevApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => DevRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/imperial-vault': typeof ImperialVaultRouteRouteWithChildren
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/browser': typeof BrowserRoute
  '/chat': typeof ChatRoute
  '/dev': typeof DevRouteWithChildren
  '/memory': typeof MemoryRoute
  '/pipelines': typeof PipelinesRoute
  '/dev/approvals': typeof DevApprovalsRoute
  '/imperial-vault/alerts': typeof ImperialVaultAlertsRoute
  '/imperial-vault/calendar': typeof ImperialVaultCalendarRoute
  '/imperial-vault/cookies': typeof ImperialVaultCookiesRoute
  '/imperial-vault/discord': typeof ImperialVaultDiscordRoute
  '/imperial-vault/facts': typeof ImperialVaultFactsRoute
  '/imperial-vault/footage': typeof ImperialVaultFootageRoute
  '/imperial-vault/intel': typeof ImperialVaultIntelRoute
  '/imperial-vault/intelligence': typeof ImperialVaultIntelligenceRoute
  '/imperial-vault/music': typeof ImperialVaultMusicRoute
  '/imperial-vault/overlay': typeof ImperialVaultOverlayRoute
  '/imperial-vault/pipeline': typeof ImperialVaultPipelineRoute
  '/imperial-vault/sandbox': typeof ImperialVaultSandboxRoute
  '/imperial-vault/terminal': typeof ImperialVaultTerminalRoute
  '/imperial-vault/viral-score': typeof ImperialVaultViralScoreRoute
  '/imperial-vault/': typeof ImperialVaultIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/browser': typeof BrowserRoute
  '/chat': typeof ChatRoute
  '/dev': typeof DevRouteWithChildren
  '/memory': typeof MemoryRoute
  '/pipelines': typeof PipelinesRoute
  '/dev/approvals': typeof DevApprovalsRoute
  '/imperial-vault/alerts': typeof ImperialVaultAlertsRoute
  '/imperial-vault/calendar': typeof ImperialVaultCalendarRoute
  '/imperial-vault/cookies': typeof ImperialVaultCookiesRoute
  '/imperial-vault/discord': typeof ImperialVaultDiscordRoute
  '/imperial-vault/facts': typeof ImperialVaultFactsRoute
  '/imperial-vault/footage': typeof ImperialVaultFootageRoute
  '/imperial-vault/intel': typeof ImperialVaultIntelRoute
  '/imperial-vault/intelligence': typeof ImperialVaultIntelligenceRoute
  '/imperial-vault/music': typeof ImperialVaultMusicRoute
  '/imperial-vault/overlay': typeof ImperialVaultOverlayRoute
  '/imperial-vault/pipeline': typeof ImperialVaultPipelineRoute
  '/imperial-vault/sandbox': typeof ImperialVaultSandboxRoute
  '/imperial-vault/terminal': typeof ImperialVaultTerminalRoute
  '/imperial-vault/viral-score': typeof ImperialVaultViralScoreRoute
  '/imperial-vault': typeof ImperialVaultIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/imperial-vault': typeof ImperialVaultRouteRouteWithChildren
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/browser': typeof BrowserRoute
  '/chat': typeof ChatRoute
  '/dev': typeof DevRouteWithChildren
  '/memory': typeof MemoryRoute
  '/pipelines': typeof PipelinesRoute
  '/dev/approvals': typeof DevApprovalsRoute
  '/imperial-vault/alerts': typeof ImperialVaultAlertsRoute
  '/imperial-vault/calendar': typeof ImperialVaultCalendarRoute
  '/imperial-vault/cookies': typeof ImperialVaultCookiesRoute
  '/imperial-vault/discord': typeof ImperialVaultDiscordRoute
  '/imperial-vault/facts': typeof ImperialVaultFactsRoute
  '/imperial-vault/footage': typeof ImperialVaultFootageRoute
  '/imperial-vault/intel': typeof ImperialVaultIntelRoute
  '/imperial-vault/intelligence': typeof ImperialVaultIntelligenceRoute
  '/imperial-vault/music': typeof ImperialVaultMusicRoute
  '/imperial-vault/overlay': typeof ImperialVaultOverlayRoute
  '/imperial-vault/pipeline': typeof ImperialVaultPipelineRoute
  '/imperial-vault/sandbox': typeof ImperialVaultSandboxRoute
  '/imperial-vault/terminal': typeof ImperialVaultTerminalRoute
  '/imperial-vault/viral-score': typeof ImperialVaultViralScoreRoute
  '/imperial-vault/': typeof ImperialVaultIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/imperial-vault'
    | '/agents'
    | '/analytics'
    | '/browser'
    | '/chat'
    | '/dev'
    | '/memory'
    | '/pipelines'
    | '/dev/approvals'
    | '/imperial-vault/alerts'
    | '/imperial-vault/calendar'
    | '/imperial-vault/cookies'
    | '/imperial-vault/discord'
    | '/imperial-vault/facts'
    | '/imperial-vault/footage'
    | '/imperial-vault/intel'
    | '/imperial-vault/intelligence'
    | '/imperial-vault/music'
    | '/imperial-vault/overlay'
    | '/imperial-vault/pipeline'
    | '/imperial-vault/sandbox'
    | '/imperial-vault/terminal'
    | '/imperial-vault/viral-score'
    | '/imperial-vault/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/analytics'
    | '/browser'
    | '/chat'
    | '/dev'
    | '/memory'
    | '/pipelines'
    | '/dev/approvals'
    | '/imperial-vault/alerts'
    | '/imperial-vault/calendar'
    | '/imperial-vault/cookies'
    | '/imperial-vault/discord'
    | '/imperial-vault/facts'
    | '/imperial-vault/footage'
    | '/imperial-vault/intel'
    | '/imperial-vault/intelligence'
    | '/imperial-vault/music'
    | '/imperial-vault/overlay'
    | '/imperial-vault/pipeline'
    | '/imperial-vault/sandbox'
    | '/imperial-vault/terminal'
    | '/imperial-vault/viral-score'
    | '/imperial-vault'
  id:
    | '__root__'
    | '/'
    | '/imperial-vault'
    | '/agents'
    | '/analytics'
    | '/browser'
    | '/chat'
    | '/dev'
    | '/memory'
    | '/pipelines'
    | '/dev/approvals'
    | '/imperial-vault/alerts'
    | '/imperial-vault/calendar'
    | '/imperial-vault/cookies'
    | '/imperial-vault/discord'
    | '/imperial-vault/facts'
    | '/imperial-vault/footage'
    | '/imperial-vault/intel'
    | '/imperial-vault/intelligence'
    | '/imperial-vault/music'
    | '/imperial-vault/overlay'
    | '/imperial-vault/pipeline'
    | '/imperial-vault/sandbox'
    | '/imperial-vault/terminal'
    | '/imperial-vault/viral-score'
    | '/imperial-vault/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImperialVaultRouteRoute: typeof ImperialVaultRouteRouteWithChildren
  AgentsRoute: typeof AgentsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BrowserRoute: typeof BrowserRoute
  ChatRoute: typeof ChatRoute
  DevRoute: typeof DevRouteWithChildren
  MemoryRoute: typeof MemoryRoute
  PipelinesRoute: typeof PipelinesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pipelines': {
      id: '/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof PipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browser': {
      id: '/browser'
      path: '/browser'
      fullPath: '/browser'
      preLoaderRoute: typeof BrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imperial-vault': {
      id: '/imperial-vault'
      path: '/imperial-vault'
      fullPath: '/imperial-vault'
      preLoaderRoute: typeof ImperialVaultRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imperial-vault/': {
      id: '/imperial-vault/'
      path: '/'
      fullPath: '/imperial-vault/'
      preLoaderRoute: typeof ImperialVaultIndexRouteImport
      parentRoute: typeof ImperialVaultRouteRoute
    }
    '/imperial-vault/viral-score': {
      id: '/imperial-vault/viral-score'
      path: '/viral-score'
      fullPath: '/imperial-vault/viral-score'
      preLoaderRoute: typeof ImperialVaultViralScoreRouteImport
      parentRoute: typeof ImperialVaultRouteRoute
    }
    '/imperial-vault/terminal': {
      id: '/imperial-vault/terminal'
      path: '/terminal'
      fullPath: '/imperial-vault/terminal'
      preLoaderRoute: typeof ImperialVaultTerminalRouteImport
      parentRoute: typeof ImperialVaultRouteRoute
    }
    '/imperial-vault/sandbox': {
      id: '/imperial-vault/sandbox'
      path: '/sandbox'
      fullPath: '/imperial-vault/sandbox'
      preLoaderRoute: typeof ImperialVaultSandboxRouteImport
      parentRoute: typeof ImperialVaultRouteRoute
    }
    '/imperial-vault/pipeline': {
      id: '/imperial-vault/pipeline'
      path: '/pipeline'
      fullPath: '/imperial-vault/pipeline'
      preLoaderRoute: typeof ImperialVaultPipelineRouteImport
      parentRoute: typeof ImperialVaultRouteRoute
    }
    '/imperial-vault/overlay': {
      id: '/imperial-vault/overlay'
      path: '/overlay'
      fullPath: '/imperial-vault/overlay'
      preLoaderRoute: typeof ImperialVaultOverlayRouteImport
      parentRoute: typeof ImperialVaultRouteRoute
    }
    '/imperial-vault/music': {
      id: '/imperial-vault/music'
      path: '/music'
      fullPath: '/imperial-vault/music'
      preLoaderRoute: typeof ImperialVaultMusicRouteImport
      parentRoute: typeof ImperialVaultRouteRoute
    }
    '/imperial-vault/intelligence': {
      id: '/imperial-vault/intelligence'
      path: '/intelligence'
      fullPath: '/imperial-vault/intelligence'
      preLoaderRoute: typeof ImperialVaultIntelligenceRouteImport
      parentRoute: typeof ImperialVaultRouteRoute
    }
    '/imperial-vault/intel': {
      id: '/imperial-vault/intel'
      path: '/intel'
      fullPath: '/imperial-vault/intel'
      preLoaderRoute: typeof ImperialVaultIntelRouteImport
      parentRoute: typeof ImperialVaultRouteRoute
    }
    '/imperial-vault/footage': {
      id: '/imperial-vault/footage'
      path: '/footage'
      fullPath: '/imperial-vault/footage'
      preLoaderRoute: typeof ImperialVaultFootageRouteImport
      parentRoute: typeof ImperialVaultRouteRoute
    }
    '/imperial-vault/facts': {
      id: '/imperial-vault/facts'
      path: '/facts'
      fullPath: '/imperial-vault/facts'
      preLoaderRoute: typeof ImperialVaultFactsRouteImport
      parentRoute: typeof ImperialVaultRouteRoute
    }
    '/imperial-vault/discord': {
      id: '/imperial-vault/discord'
      path: '/discord'
      fullPath: '/imperial-vault/discord'
      preLoaderRoute: typeof ImperialVaultDiscordRouteImport
      parentRoute: typeof ImperialVaultRouteRoute
    }
    '/imperial-vault/cookies': {
      id: '/imperial-vault/cookies'
      path: '/cookies'
      fullPath: '/imperial-vault/cookies'
      preLoaderRoute: typeof ImperialVaultCookiesRouteImport
      parentRoute: typeof ImperialVaultRouteRoute
    }
    '/imperial-vault/calendar': {
      id: '/imperial-vault/calendar'
      path: '/calendar'
      fullPath: '/imperial-vault/calendar'
      preLoaderRoute: typeof ImperialVaultCalendarRouteImport
      parentRoute: typeof ImperialVaultRouteRoute
    }
    '/imperial-vault/alerts': {
      id: '/imperial-vault/alerts'
      path: '/alerts'
      fullPath: '/imperial-vault/alerts'
      preLoaderRoute: typeof ImperialVaultAlertsRouteImport
      parentRoute: typeof ImperialVaultRouteRoute
    }
    '/dev/approvals': {
      id: '/dev/approvals'
      path: '/approvals'
      fullPath: '/dev/approvals'
      preLoaderRoute: typeof DevApprovalsRouteImport
      parentRoute: typeof DevRoute
    }
  }
}

interface ImperialVaultRouteRouteChildren {
  ImperialVaultAlertsRoute: typeof ImperialVaultAlertsRoute
  ImperialVaultCalendarRoute: typeof ImperialVaultCalendarRoute
  ImperialVaultCookiesRoute: typeof ImperialVaultCookiesRoute
  ImperialVaultDiscordRoute: typeof ImperialVaultDiscordRoute
  ImperialVaultFactsRoute: typeof ImperialVaultFactsRoute
  ImperialVaultFootageRoute: typeof ImperialVaultFootageRoute
  ImperialVaultIntelRoute: typeof ImperialVaultIntelRoute
  ImperialVaultIntelligenceRoute: typeof ImperialVaultIntelligenceRoute
  ImperialVaultMusicRoute: typeof ImperialVaultMusicRoute
  ImperialVaultOverlayRoute: typeof ImperialVaultOverlayRoute
  ImperialVaultPipelineRoute: typeof ImperialVaultPipelineRoute
  ImperialVaultSandboxRoute: typeof ImperialVaultSandboxRoute
  ImperialVaultTerminalRoute: typeof ImperialVaultTerminalRoute
  ImperialVaultViralScoreRoute: typeof ImperialVaultViralScoreRoute
  ImperialVaultIndexRoute: typeof ImperialVaultIndexRoute
}

const ImperialVaultRouteRouteChildren: ImperialVaultRouteRouteChildren = {
  ImperialVaultAlertsRoute: ImperialVaultAlertsRoute,
  ImperialVaultCalendarRoute: ImperialVaultCalendarRoute,
  ImperialVaultCookiesRoute: ImperialVaultCookiesRoute,
  ImperialVaultDiscordRoute: ImperialVaultDiscordRoute,
  ImperialVaultFactsRoute: ImperialVaultFactsRoute,
  ImperialVaultFootageRoute: ImperialVaultFootageRoute,
  ImperialVaultIntelRoute: ImperialVaultIntelRoute,
  ImperialVaultIntelligenceRoute: ImperialVaultIntelligenceRoute,
  ImperialVaultMusicRoute: ImperialVaultMusicRoute,
  ImperialVaultOverlayRoute: ImperialVaultOverlayRoute,
  ImperialVaultPipelineRoute: ImperialVaultPipelineRoute,
  ImperialVaultSandboxRoute: ImperialVaultSandboxRoute,
  ImperialVaultTerminalRoute: ImperialVaultTerminalRoute,
  ImperialVaultViralScoreRoute: ImperialVaultViralScoreRoute,
  ImperialVaultIndexRoute: ImperialVaultIndexRoute,
}

const ImperialVaultRouteRouteWithChildren =
  ImperialVaultRouteRoute._addFileChildren(ImperialVaultRouteRouteChildren)

interface DevRouteChildren {
  DevApprovalsRoute: typeof DevApprovalsRoute
}

const DevRouteChildren: DevRouteChildren = {
  DevApprovalsRoute: DevApprovalsRoute,
}

const DevRouteWithChildren = DevRoute._addFileChildren(DevRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImperialVaultRouteRoute: ImperialVaultRouteRouteWithChildren,
  AgentsRoute: AgentsRoute,
  AnalyticsRoute: AnalyticsRoute,
  BrowserRoute: BrowserRoute,
  ChatRoute: ChatRoute,
  DevRoute: DevRouteWithChildren,
  MemoryRoute: MemoryRoute,
  PipelinesRoute: PipelinesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
